### ISSUE TITLE
Browser - Which one ?

### ISSUE THREAD

**Issue by SuperITMan** [BetterLineage/android_prebuilts_prebuiltapks#7]
Hey @qwow5 

I think that we should take time to compare the different browsers available on F-Droid, or somewhere else, to see which one could be the best. 

Here you can find a list with some browsers available on F-Droid:

| Browsers | Release date | Size | Leight |
|-------------|-------------------| ----- | -------- |
| [DuckDuckGo Privacy Browser](https://f-droid.org/en/packages/com.duckduckgo.mobile.android) | 12-10-2019 | 9.2 MiB | :heavy_check_mark: |
| [Fennec F-Droid](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid) | 27-10-2019 | 56.5 MiB | :x: |
| [Firefox Klar](https://f-droid.org/en/packages/org.mozilla.klar) | 11-07-2019 | 48.4 MiB | :x: |
| [Firefox Lite](https://f-droid.org/en/packages/org.mozilla.rocket) | 01-05-2019 | 3.3 MiB | :heavy_check_mark: |
| [FOSS Browser](https://f-droid.org/en/packages/de.baumann.browser) | 19-09-2019 | 2.7 MiB | :heavy_check_mark: |
| [IceCatMobile](https://f-droid.org/en/packages/org.gnu.icecat) | 19-02-2019 | 40.6 MiB | :x: |
| [Lightning](https://f-droid.org/en/packages/acr.browser.lightning/) | 02-11-2019 | 3.3 MiB | :heavy_check_mark: |
| ... | ... | ... | ... |

We should pay attention to propose a default browser always up to date.
If we cannot, why not simply keeping the default browser proposed by LineageOS ?

**Comment by qwow5** [comment]
@SuperITMan

I chose the DuckDuckGo Privacy Browser because it is kept up to date and is stable. Fennec and IceCat both crashed when open, Firefox Lite worked great, but was not kept up to date. DuckDuckGo meets all of these requirements for a browser.
