### ISSUE TITLE
F-Droid vs AuroraDroid

### ISSUE THREAD

**Issue by SuperITMan** [BetterLineage/android_prebuilts_prebuiltapks#8]
Hi @qwow5 

I saw the different changes you made about F-Droid and AuroraDroid.

Could you please document why we should use one or the other? :blush:

**Comment by qwow5** [comment]
@SuperITMan

I chose to go back to F-Droid because the script that automatically adds the microG F-Droid repository (located under additional_repos) only works with the official F-Droid client.
